# Generated by Django 5.0.1 on 2024-01-17 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotografia',
            name='categoria',
            field=models.CharField(choices=[('Nebulosa', 'nebulosa'), ('Estrela', 'estrela'), ('Galaxia', 'galaxia'), ('Planeta', 'planeta')], default='', max_length=100),
        ),
    ]
